kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build & publish  
    image: docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - "docker build --build-arg MAKEFLAGS=-j6 --build-arg VERSION=4.5.0 -t l4t-opencv:test ."

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock