kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build & publish  
  image: plugins/docker
  settings:
    repo: zauberzeug/l4t-opencv
    build_args:
     - MAKEFLAGS=-j6
     - VERSION=4.5.0
    tags:
     - latest
     - 4.5.0-r32.4.4-nano

