kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build  
    image: docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - "docker build --build-arg MAKEFLAGS=-j6 --build-arg OPENCV_VERSION=4.5.0 -t l4t-opencv:4.5.0-on-nano-r32.4.4 ."

  - name: publish  
    image: docker
    environment:
      PASSWORD:
        from_secret: zauberzeug_docker_password
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - "docker -D login -u zauberzeug -p '$${PASSWORD}'"
      - "docker push l4t-opencv:4.5.0-on-nano-r32.4.4"

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock